//! In-memory session store: sessions, messages, statuses, diffs, todos, and revert info.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// A conversation session stored in the local context cache.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Session {
    pub id: String,
    pub title: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub parent_id: Option<String>,
    pub share: Option<ShareInfo>,
}

/// Public share information for a session.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ShareInfo {
    pub url: String,
}

/// A single message in a session, including all typed parts and metadata.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Message {
    pub id: String,
    pub role: MessageRole,
    pub content: String,
    pub created_at: DateTime<Utc>,
    pub agent: Option<String>,
    pub model: Option<String>,
    pub mode: Option<String>,
    pub finish: Option<String>,
    pub error: Option<String>,
    pub completed_at: Option<DateTime<Utc>>,
    pub cost: f64,
    pub tokens: TokenUsage,
    pub parts: Vec<MessagePart>,
}

/// The author role of a message.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum MessageRole {
    /// Message sent by the human user.
    User,
    /// Message generated by the AI assistant.
    Assistant,
    /// System-level instruction message.
    System,
}

/// Token consumption breakdown for a single message.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TokenUsage {
    pub input: u64,
    pub output: u64,
    pub reasoning: u64,
    pub cache_read: u64,
    pub cache_write: u64,
}

/// A typed content segment within a message.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum MessagePart {
    /// Plain text content.
    Text {
        text: String,
    },
    /// Extended reasoning / thinking block.
    Reasoning {
        text: String,
    },
    /// An attached file.
    File {
        path: String,
        mime: String,
    },
    /// An inline image.
    Image {
        url: String,
    },
    /// A tool invocation request.
    ToolCall {
        id: String,
        name: String,
        arguments: String,
    },
    /// The output of a tool invocation.
    ToolResult {
        id: String,
        result: String,
        is_error: bool,
    },
}

/// In-memory store for all sessions, messages, statuses, diffs, todos, and revert info.
#[derive(Clone, Debug, Default)]
pub struct SessionContext {
    pub sessions: HashMap<String, Session>,
    pub messages: HashMap<String, Vec<Message>>,
    pub current_session_id: Option<String>,
    pub session_status: HashMap<String, SessionStatus>,
    pub session_diff: HashMap<String, Vec<DiffEntry>>,
    pub todos: HashMap<String, Vec<TodoItem>>,
    pub revert: HashMap<String, RevertInfo>,
}

/// The run state of a session.
#[derive(Clone, Debug)]
pub enum SessionStatus {
    /// No active run — the session is waiting for input.
    Idle,
    /// The session is actively processing a request.
    Running,
    /// The session is retrying after a transient error.
    Retrying {
        message: String,
        attempt: u32,
        next: i64,
    },
}

impl Default for SessionStatus {
    fn default() -> Self {
        Self::Idle
    }
}

/// A single file change entry in a session diff.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DiffEntry {
    pub file: String,
    pub additions: u32,
    pub deletions: u32,
}

/// Checkpoint data used to revert a session to a previous message.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RevertInfo {
    pub message_id: String,
    pub part_id: Option<String>,
    pub snapshot: Option<String>,
    pub diff: Option<String>,
}

/// A single item in the session's todo list.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TodoItem {
    pub content: String,
    pub status: TodoStatus,
}

/// Completion state of a todo item.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum TodoStatus {
    /// Not yet started.
    Pending,
    /// Currently being worked on.
    InProgress,
    /// Successfully finished.
    Completed,
    /// Abandoned without completion.
    Cancelled,
}

impl SessionContext {
    pub fn new() -> Self {
        Self::default()
    }

    /// Return the active session, if one is set.
    pub fn current_session(&self) -> Option<&Session> {
        self.current_session_id
            .as_ref()
            .and_then(|id| self.sessions.get(id))
    }

    /// Return references to all messages in the active session.
    pub fn current_messages(&self) -> Vec<&Message> {
        self.current_session_id
            .as_ref()
            .and_then(|id| self.messages.get(id))
            .map(|m| m.iter().collect())
            .unwrap_or_default()
    }

    /// Create a new session with an optional title and make it current.
    pub fn create_session(&mut self, title: Option<String>) -> String {
        let id = uuid::Uuid::new_v4().to_string();
        let now = Utc::now();
        let session = Session {
            id: id.clone(),
            title: title.unwrap_or_else(|| "New Session".to_string()),
            created_at: now,
            updated_at: now,
            parent_id: None,
            share: None,
        };
        self.sessions.insert(id.clone(), session);
        self.messages.insert(id.clone(), Vec::new());
        self.session_status.insert(id.clone(), SessionStatus::Idle);
        self.current_session_id = Some(id.clone());
        id
    }

    /// Insert or update a session and make it current.
    pub fn upsert_session(&mut self, session: Session) {
        let id = session.id.clone();
        self.sessions.insert(id.clone(), session);
        self.messages.entry(id.clone()).or_default();
        self.session_status
            .entry(id.clone())
            .or_insert(SessionStatus::Idle);
        self.current_session_id = Some(id);
    }

    /// Replace all messages for a session.
    pub fn set_messages(&mut self, session_id: &str, messages: Vec<Message>) {
        self.messages.insert(session_id.to_string(), messages);
    }

    /// Append a single message to a session's message list.
    pub fn add_message(&mut self, session_id: &str, message: Message) {
        if let Some(messages) = self.messages.get_mut(session_id) {
            messages.push(message);
        }
    }

    /// Update the run status for a session.
    pub fn set_status(&mut self, session_id: &str, status: SessionStatus) {
        self.session_status.insert(session_id.to_string(), status);
    }

    /// Return the current run status for a session, defaulting to `Idle`.
    pub fn status(&self, session_id: &str) -> &SessionStatus {
        self.session_status
            .get(session_id)
            .unwrap_or(&SessionStatus::Idle)
    }
}
