//! Message and conversation primitives used by the agent executor.

use serde::{Deserialize, Serialize};

/// A single message in an agent conversation, carrying a role, text content, and any tool calls.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentMessage {
    /// The role of the message sender (system, user, assistant, or tool).
    pub role: MessageRole,
    /// The text content of the message.
    pub content: String,
    /// Tool calls requested by the assistant in this message, if any.
    pub tool_calls: Vec<ToolCall>,
}

/// The role of a participant in a conversation turn.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MessageRole {
    /// A system-level instruction message.
    System,
    /// A message from the human user.
    User,
    /// A message generated by the AI assistant.
    Assistant,
    /// A message carrying the result of a tool invocation.
    Tool,
}

/// A tool invocation requested by the assistant, including its identifier, name, and arguments.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Unique identifier for this tool call, used to correlate results.
    pub id: String,
    /// The name of the tool to invoke.
    pub name: String,
    /// JSON arguments to pass to the tool.
    pub arguments: serde_json::Value,
}

/// The result returned after executing a tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    /// The identifier of the tool call this result corresponds to.
    pub tool_call_id: String,
    /// The name of the tool that was executed.
    pub name: String,
    /// The output produced by the tool.
    pub content: String,
    /// Whether the tool execution resulted in an error.
    pub is_error: bool,
}

impl AgentMessage {
    /// Creates a system message with the given content.
    /// Creates a system message with the given content.
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: MessageRole::System,
            content: content.into(),
            tool_calls: Vec::new(),
        }
    }

    /// Creates a user message with the given content.
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: MessageRole::User,
            content: content.into(),
            tool_calls: Vec::new(),
        }
    }

    /// Creates an assistant message with the given content and no tool calls.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: MessageRole::Assistant,
            content: content.into(),
            tool_calls: Vec::new(),
        }
    }

    /// Creates an assistant message that includes one or more tool calls.
    pub fn assistant_with_tools(content: impl Into<String>, tool_calls: Vec<ToolCall>) -> Self {
        Self {
            role: MessageRole::Assistant,
            content: content.into(),
            tool_calls,
        }
    }

    /// Creates a tool-result message carrying the output of a tool invocation.
    pub fn tool_result(
        _tool_call_id: impl Into<String>,
        _name: impl Into<String>,
        content: impl Into<String>,
        _is_error: bool,
    ) -> Self {
        Self {
            role: MessageRole::Tool,
            content: content.into(),
            tool_calls: vec![],
        }
    }
}

/// An ordered sequence of messages that forms a single agent conversation thread.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conversation {
    /// All messages in the conversation, in chronological order.
    pub messages: Vec<AgentMessage>,
}

impl Conversation {
    /// Creates an empty conversation with no messages.
    /// Creates an empty conversation with no messages.
    pub fn new() -> Self {
        Self {
            messages: Vec::new(),
        }
    }

    /// Creates a conversation pre-seeded with a system prompt as the first message.
    pub fn with_system_prompt(prompt: impl Into<String>) -> Self {
        let mut conv = Self::new();
        conv.messages.push(AgentMessage::system(prompt));
        conv
    }

    /// Appends a user message to the conversation.
    pub fn add_user_message(&mut self, content: impl Into<String>) {
        self.messages.push(AgentMessage::user(content));
    }

    /// Appends an assistant message to the conversation.
    pub fn add_assistant_message(&mut self, content: impl Into<String>) {
        self.messages.push(AgentMessage::assistant(content));
    }

    /// Appends a tool-result message to the conversation.
    pub fn add_tool_result(
        &mut self,
        tool_call_id: impl Into<String>,
        name: impl Into<String>,
        content: impl Into<String>,
        is_error: bool,
    ) {
        self.messages.push(AgentMessage::tool_result(
            tool_call_id,
            name,
            content,
            is_error,
        ));
    }

    /// Converts all messages to the provider-facing message format for use in a chat request.
    ///
    /// # Note
    /// Tool-result messages are mapped to assistant messages because the provider layer
    /// does not have a dedicated tool-result role.
    pub fn to_provider_messages(&self) -> Vec<kfcode_provider::Message> {
        self.messages
            .iter()
            .map(|m| match m.role {
                MessageRole::System => kfcode_provider::Message::system(&m.content),
                MessageRole::User => kfcode_provider::Message::user(&m.content),
                MessageRole::Assistant => kfcode_provider::Message::assistant(&m.content),
                MessageRole::Tool => kfcode_provider::Message::assistant(&m.content),
            })
            .collect()
    }
}

impl Default for Conversation {
    fn default() -> Self {
        Self::new()
    }
}
